<?php
add_action( 'init', function() {
	register_post_type( 'education', array(
	'labels' => array(
		'name' => 'Educations',
		'singular_name' => 'Education',
		'menu_name' => 'Educations',
		'all_items' => 'All Educations',
		'edit_item' => 'Edit Education',
		'view_item' => 'View Education',
		'view_items' => 'View Educations',
		'add_new_item' => 'Add New Education',
		'add_new' => 'Add New Education',
		'new_item' => 'New Education',
		'parent_item_colon' => 'Parent Education:',
		'search_items' => 'Search Educations',
		'not_found' => 'No educations found',
		'not_found_in_trash' => 'No educations found in Trash',
		'archives' => 'Education Archives',
		'attributes' => 'Education Attributes',
		'insert_into_item' => 'Insert into education',
		'uploaded_to_this_item' => 'Uploaded to this education',
		'filter_items_list' => 'Filter educations list',
		'filter_by_date' => 'Filter educations by date',
		'items_list_navigation' => 'Educations list navigation',
		'items_list' => 'Educations list',
		'item_published' => 'Education published.',
		'item_published_privately' => 'Education published privately.',
		'item_reverted_to_draft' => 'Education reverted to draft.',
		'item_scheduled' => 'Education scheduled.',
		'item_updated' => 'Education updated.',
		'item_link' => 'Education Link',
		'item_link_description' => 'A link to a education.',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-welcome-learn-more',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'experience', array(
	'labels' => array(
		'name' => 'Experiences',
		'singular_name' => 'Experience',
		'menu_name' => 'Experience',
		'all_items' => 'All experience',
		'edit_item' => 'Edit experience',
		'view_item' => 'View experience',
		'view_items' => 'View experience',
		'add_new_item' => 'Add New experience',
		'add_new' => 'Add New experience',
		'new_item' => 'New experience',
		'parent_item_colon' => 'Parent experience:',
		'search_items' => 'Search experience',
		'not_found' => 'No experience found',
		'not_found_in_trash' => 'No experience found in Trash',
		'archives' => 'experience Archives',
		'attributes' => 'experience Attributes',
		'insert_into_item' => 'Insert into experience',
		'uploaded_to_this_item' => 'Uploaded to this experience',
		'filter_items_list' => 'Filter experience list',
		'filter_by_date' => 'Filter experience by date',
		'items_list_navigation' => 'experience list navigation',
		'items_list' => 'exprean list',
		'item_published' => 'experience published.',
		'item_published_privately' => 'experience published privately.',
		'item_reverted_to_draft' => 'experience reverted to draft.',
		'item_scheduled' => 'experience scheduled.',
		'item_updated' => 'experience updated.',
		'item_link' => 'experience Link',
		'item_link_description' => 'A link to a experience.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-buddicons-buddypress-logo',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'projects', array(
	'labels' => array(
		'name' => 'Projects',
		'singular_name' => 'Projects',
		'menu_name' => 'Projects',
		'all_items' => 'All Projects',
		'edit_item' => 'Edit Projects',
		'view_item' => 'View Projects',
		'view_items' => 'View Projects',
		'add_new_item' => 'Add New Projects',
		'add_new' => 'Add New Projects',
		'new_item' => 'New Projects',
		'parent_item_colon' => 'Parent Projects:',
		'search_items' => 'Search Projects',
		'not_found' => 'No projects found',
		'not_found_in_trash' => 'No projects found in Trash',
		'archives' => 'Projects Archives',
		'attributes' => 'Projects Attributes',
		'featured_image' => 'Project Feature',
		'set_featured_image' => 'Set Project Feature',
		'remove_featured_image' => 'Remove Project Feature',
		'use_featured_image' => 'Use Project Feature',
		'insert_into_item' => 'Insert into projects',
		'uploaded_to_this_item' => 'Uploaded to this projects',
		'filter_items_list' => 'Filter projects list',
		'filter_by_date' => 'Filter projects by date',
		'items_list_navigation' => 'Projects list navigation',
		'items_list' => 'Projects list',
		'item_published' => 'Projects published.',
		'item_published_privately' => 'Projects published privately.',
		'item_reverted_to_draft' => 'Projects reverted to draft.',
		'item_scheduled' => 'Projects scheduled.',
		'item_updated' => 'Projects updated.',
		'item_link' => 'Projects Link',
		'item_link_description' => 'A link to a projects.',
	),
	'public' => true,
	'hierarchical' => true,
	'exclude_from_search' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-schedule',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
		2 => 'thumbnail',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'service', array(
	'labels' => array(
		'name' => 'Services',
		'singular_name' => 'Service',
		'menu_name' => 'Services',
		'all_items' => 'All Services',
		'edit_item' => 'Edit Service',
		'view_item' => 'View Service',
		'view_items' => 'View Services',
		'add_new_item' => 'Add New Service',
		'add_new' => 'Add New Service',
		'new_item' => 'New Service',
		'parent_item_colon' => 'Parent Service:',
		'search_items' => 'Search Services',
		'not_found' => 'No services found',
		'not_found_in_trash' => 'No services found in Trash',
		'archives' => 'Service Archives',
		'attributes' => 'Service Attributes',
		'insert_into_item' => 'Insert into service',
		'uploaded_to_this_item' => 'Uploaded to this service',
		'filter_items_list' => 'Filter services list',
		'filter_by_date' => 'Filter services by date',
		'items_list_navigation' => 'Services list navigation',
		'items_list' => 'Services list',
		'item_published' => 'Service published.',
		'item_published_privately' => 'Service published privately.',
		'item_reverted_to_draft' => 'Service reverted to draft.',
		'item_scheduled' => 'Service scheduled.',
		'item_updated' => 'Service updated.',
		'item_link' => 'Service Link',
		'item_link_description' => 'A link to a service.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-admin-generic',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'teatimonial', array(
	'labels' => array(
		'name' => 'Teatimonials',
		'singular_name' => 'Teatimonial',
		'menu_name' => 'Teatimonials',
		'all_items' => 'All Teatimonials',
		'edit_item' => 'Edit Teatimonial',
		'view_item' => 'View Teatimonial',
		'view_items' => 'View Teatimonials',
		'add_new_item' => 'Add New Teatimonial',
		'add_new' => 'Add New Teatimonial',
		'new_item' => 'New Teatimonial',
		'parent_item_colon' => 'Parent Teatimonial:',
		'search_items' => 'Search Teatimonials',
		'not_found' => 'No teatimonials found',
		'not_found_in_trash' => 'No teatimonials found in Trash',
		'archives' => 'Teatimonial Archives',
		'attributes' => 'Teatimonial Attributes',
		'featured_image' => 'Profile Image',
		'set_featured_image' => 'Set Profile Image',
		'remove_featured_image' => 'Remove Profile Image',
		'use_featured_image' => 'Use Profile Image',
		'insert_into_item' => 'Insert into teatimonial',
		'uploaded_to_this_item' => 'Uploaded to this teatimonial',
		'filter_items_list' => 'Filter teatimonials list',
		'filter_by_date' => 'Filter teatimonials by date',
		'items_list_navigation' => 'Teatimonials list navigation',
		'items_list' => 'Teatimonials list',
		'item_published' => 'Teatimonial published.',
		'item_published_privately' => 'Teatimonial published privately.',
		'item_reverted_to_draft' => 'Teatimonial reverted to draft.',
		'item_scheduled' => 'Teatimonial scheduled.',
		'item_updated' => 'Teatimonial updated.',
		'item_link' => 'Teatimonial Link',
		'item_link_description' => 'A link to a teatimonial.',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-image-flip-horizontal',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
		2 => 'thumbnail',
	),
	'delete_with_user' => false,
) );
} );


add_filter( 'enter_title_here', function( $default, $post ) {
	switch ( $post->post_type ) {
		case 'education':
			return 'Name of Degree';
		case 'experience':
			return 'Job Position';
		case 'projects':
			return 'Project Title';
		case 'service':
			return 'Services Title';
	}

	return $default;
}, 10, 2 );